### ISSUE TITLE
Setup Branch Security

### ISSUE THREAD

**Issue by brandonapol** [Kkoder27/projectForGrownUps#1]
Protect the main branch

[Github Branch Protection](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule)

**Comment by KillianMBrunswick** [comment]
Required main branch pull request to be approved by at least 1 collaborator. Please review

**Comment by brandonapol** [comment]
<img width="1225" alt="Screen Shot 2024-01-02 at 9 46 59 AM" src="https://github.com/Kkoder27/projectForGrownUps/assets/72466214/b4616306-500c-45b6-8733-806adae7e368">

Show me screen shot with this for your repo - I cannot access settings to this repository, so I can't see 🙂

**Comment by KillianMBrunswick** [comment]
![branchProofs](https://github.com/Kkoder27/projectForGrownUps/assets/124717647/917231cc-9621-4c2c-bb6d-5cfe357b6929)
